<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ArtikelSeeder extends Seeder
{
    public function run()
    {

        $data = [
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567890',
                'slug' => 'bekerjasama-dengan-pemerintah-desa-bulo-bulo-pkm-salsase-berikan-layanan-kesehatan-gratis-untuk-masyarakat',
                'judul' => 'Bekerjasama dengan Pemerintah Desa Bulo-Bulo PKM Salsase Berikan Layanan Kesehatan Gratis untuk Masyarakat',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'bekerjasama-dengan-pemerintah-desa-bulo-bulo-pkm-salsase-berikan-layanan-kesehatan-gratis-untuk-masyarakat.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'News',
                'level' => 'main',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567891',
                'slug' => 'berikan-sambutan-di-pelantikan-pantarlik-kades-bulo-bulo-penyelenggara-itu-berintegritas',
                'judul' => 'Berikan Sambutan di Pelantikan Pantarlik Kades Bulo-Bulo Penyelenggara Itu Berintegritas',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'berikan-sambutan-di-pelantikan-pantarlik-kades-bulo-bulo-penyelenggara-itu-berintegritas.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Politik',
                'level' => 'main',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567892',
                'slug' => 'catatan-menjemput-musyda-dpd-imm-sulawesi-selatan',
                'judul' => 'Catatan Menjemput Musyda DPD IMM Sulawesi Selatan',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'catatan-menjemput-musyda-dpd-imm-sulawesi-selatan.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Opini',
                'level' => 'main',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567893',
                'slug' => 'enviromental-etik-dalam-pusaran-pesta-demokrasi',
                'judul' => 'Enviromental Etik dalam Pusaran Pesta Demokrasi',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'enviromental-etik-dalam-pusaran-pesta-demokrasi.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Politik',
                'level' => 'main',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567894',
                'slug' => 'fakultas-kip-umb-lepas-172-mahasiswa-peserta-kkn-tematik',
                'judul' => 'Fakultas KIP UMB Lepas 172 Mahasiswa Peserta KKN Tematik',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'fakultas-kip-umb-lepas-172-mahasiswa-peserta-kkn-tematik.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'News',
                'level' => 'main',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567895',
                'slug' => 'gelar-kajian-kepemimpinan-pikom-imm-ilmu-aktuaria-umb-hadirkan-ketum-pc-imm-bulukumba',
                'judul' => 'Gelar Kajian Kepemimpinan Pikom IMM Ilmu Aktuaria UMB Hadirkan Ketum PC IMM Bulukumba',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'gelar-kajian-kepemimpinan-pikom-imm-ilmu-aktuaria-umb-hadirkan-ketum-pc-imm-bulukumba.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'News',
                'level' => 'main',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567896',
                'slug' => 'gerakan-bangun-negeri-kolaborasi-dengan-binroh-hindu-telkom-ajarkan-pendidikan-karakter-di-pasraman-hindu',
                'judul' => 'Gerakan Bangun Negeri Kolaborasi dengan Binroh Hindu Telkom Ajarkan Pendidikan Karakter di Pasraman Hindu',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'gerakan-bangun-negeri-kolaborasi-dengan-binroh-hindu-telkom-ajarkan-pendidikan-karakter-di-pasraman-hindu.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Teologi',
                'level' => 'general',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567877',
                'slug' => 'ibu-kota-negara-baru-untuk-keberlanjutan-nasional',
                'judul' => 'Ibu Kota Negara Baru untuk Keberlanjutan Nasional',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'ibu-kota-negara-baru-untuk-keberlanjutan-nasional.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Sosial',
                'level' => 'general',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567888',
                'slug' => 'logika-dan-pentingnya-rasionalitas-argumentasi',
                'judul' => 'Logika dan Pentingnya Rasionalitas Argumentasi',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'logika-dan-pentingnya-rasionalitas-argumentasi.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Filsafat',
                'level' => 'general',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1234567899',
                'slug' => 'media-sosial-bagi-pelajar-zaman-sekarang',
                'judul' => 'Media Sosial bagi Pelajar Zaman Sekarang',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'media-sosial-bagi-pelajar-zaman-sekarang.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Opini',
                'level' => 'general',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '1134567890',
                'slug' => 'memaknai-humanisme-dalam-konteks-kemuhammadiyahan',
                'judul' => 'Memaknai Humanisme dalam Konteks Kemuhammadiyahan',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'memaknai-humanisme-dalam-konteks-kemuhammadiyahan.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Teologi',
                'level' => 'general',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '2234567890',
                'slug' => 'pengaruh-pengelolaan-sumber-daya-alam-yang-membabi-buta',
                'judul' => 'Pengaruh Pengelolaan Sumber Daya Alam yang Membabi Buta',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'pengaruh-pengelolaan-sumber-daya-alam-yang-membabi-buta.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Sosial',
                'level' => 'general',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '3334567890',
                'slug' => 'pesan-khidmat-bapak-ardiansyah-spdpmdp-kepala-desa-pakubalaho-terpilih',
                'judul' => 'Pesan Khidmat Bapak Ardiansyah SPDPMDP Kepala Desa Pakubalaho Terpilih',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'pesan-khidmat-bapak-ardiansyah-spdpmdp-kepala-desa-pakubalaho-terpilih.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Politik',
                'level' => 'populer-post',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '4434567890',
                'slug' => 'pikiran-dan-pengetahuan-yang-benar',
                'judul' => 'Pikiran dan Pengetahuan yang Benar',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'pikiran-dan-pengetahuan-yang-benar.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Filsafat',
                'level' => 'populer-post',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '5534567890',
                'slug' => 'ratusan-warga-muhammadiyah-bulukumba-padati-pengajian-semarak-muktamar-muhammadiyah-dan-aisyiyah-ke-48',
                'judul' => 'Ratusan Warga Muhammadiyah Bulukumba Padati Pengajian Semarak Muktamar Muhammadiyah dan Aisyiyah ke-48',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'ratusan-warga-muhammadiyah-bulukumba-padati-pengajian-semarak-muktamar-muhammadiyah-dan-aisyiyah-ke-48.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'News',
                'level' => 'populer-post',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '6634567890',
                'slug' => 'sejauh-mana-bisaku-bertahan',
                'judul' => 'Sejauh Mana Bisaku Bertahan',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'sejauh-mana-bisaku-bertahan.jpg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'The Story',
                'level' => 'populer-post',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '7734567890',
                'slug' => 'um-bulukumba-gelar-penyambutan-mahasiswa-baru-melalui-masa-taaruf-dan-keakraban-mahasiswa',
                'judul' => 'UM Bulukumba Gelar Penyambutan Mahasiswa Baru melalui Masa Tarauf sebagai Ajang Keakraban Mahasiswa',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'um-bulukumba-gelar-penyambutan-mahasiswa-baru-melalui-masa-taaruf-dan-keakraban-mahasiswa.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'News',
                'level' => 'populer-post',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ],
            [
                'tanggal' => '2024-03-07',
                'yposting' => '2024',
                'waktu' => '08:00',
                'time' => '8834567890',
                'slug' => 'wujudkan-visi-sebagai-kampus-entrepreneur-mahasiswa-umb-inisiasi-mini-bazar-di-kampus',
                'judul' => 'Wujudkan Visi sebagai Kampus Entrepreneur Mahasiswa UMB Inisiasi Mini Bazaar di Kampus',
                'description' => 'Ini adalah deskripsi singkat untuk artikel ini.',
                'srcimg' => 'pintuperadaban',
                'picture' => 'wujudkan-visi-sebagai-kampus-entrepreneur-mahasiswa-umb-inisiasi-mini-bazar-di-kampus.jpeg',
                'oleh' => 'Editor Ppc',
                'kategori' => 'Ekonomi',
                'level' => 'populer-post',
                'artikel' => '<p>Data sedang dalam proses pemulihan dari database lama. Kami berharap data dapat diselamatkan dengan baik. </p>',
                'visit' => 50,
                'view' => 50,
            ]
        ];

        // Insert data ke tabel artikel
        $this->db->table('artikel')->insertBatch($data);
    }
}
